// Generated by gencpp from file robot_config/ingredient_statusResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSRESPONSE_H
#define ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_config
{
template <class ContainerAllocator>
struct ingredient_statusResponse_
{
  typedef ingredient_statusResponse_<ContainerAllocator> Type;

  ingredient_statusResponse_()
    : amount_remaining(0)  {
    }
  ingredient_statusResponse_(const ContainerAllocator& _alloc)
    : amount_remaining(0)  {
  (void)_alloc;
    }



   typedef uint32_t _amount_remaining_type;
  _amount_remaining_type amount_remaining;




  typedef boost::shared_ptr< ::robot_config::ingredient_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_config::ingredient_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ingredient_statusResponse_

typedef ::robot_config::ingredient_statusResponse_<std::allocator<void> > ingredient_statusResponse;

typedef boost::shared_ptr< ::robot_config::ingredient_statusResponse > ingredient_statusResponsePtr;
typedef boost::shared_ptr< ::robot_config::ingredient_statusResponse const> ingredient_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_config::ingredient_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_config

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::ingredient_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::ingredient_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::ingredient_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0708a1b16b87a63e45a971b9fbb2de1c";
  }

  static const char* value(const ::robot_config::ingredient_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0708a1b16b87a63eULL;
  static const uint64_t static_value2 = 0x45a971b9fbb2de1cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_config/ingredient_statusResponse";
  }

  static const char* value(const ::robot_config::ingredient_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 amount_remaining\n\
";
  }

  static const char* value(const ::robot_config::ingredient_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.amount_remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ingredient_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_config::ingredient_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_config::ingredient_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "amount_remaining: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.amount_remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSRESPONSE_H
