// Generated by gencpp from file robot_config/ingredient_statusRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSREQUEST_H
#define ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_config
{
template <class ContainerAllocator>
struct ingredient_statusRequest_
{
  typedef ingredient_statusRequest_<ContainerAllocator> Type;

  ingredient_statusRequest_()
    : header()
    , name()
    , amount(0)  {
    }
  ingredient_statusRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , amount(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint32_t _amount_type;
  _amount_type amount;




  typedef boost::shared_ptr< ::robot_config::ingredient_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_config::ingredient_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ingredient_statusRequest_

typedef ::robot_config::ingredient_statusRequest_<std::allocator<void> > ingredient_statusRequest;

typedef boost::shared_ptr< ::robot_config::ingredient_statusRequest > ingredient_statusRequestPtr;
typedef boost::shared_ptr< ::robot_config::ingredient_statusRequest const> ingredient_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_config::ingredient_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_config

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::ingredient_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::ingredient_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::ingredient_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8e51015696c1e5ef4038d0f504f6fb8";
  }

  static const char* value(const ::robot_config::ingredient_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8e51015696c1e5eULL;
  static const uint64_t static_value2 = 0xf4038d0f504f6fb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_config/ingredient_statusRequest";
  }

  static const char* value(const ::robot_config::ingredient_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
string name\n\
uint32 amount\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robot_config::ingredient_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.amount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ingredient_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_config::ingredient_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_config::ingredient_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "amount: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.amount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONFIG_MESSAGE_INGREDIENT_STATUSREQUEST_H
