// Generated by gencpp from file robot_config/user_statusResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONFIG_MESSAGE_USER_STATUSRESPONSE_H
#define ROBOT_CONFIG_MESSAGE_USER_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_config
{
template <class ContainerAllocator>
struct user_statusResponse_
{
  typedef user_statusResponse_<ContainerAllocator> Type;

  user_statusResponse_()
    : current_state(0)
    , readable_state()  {
    }
  user_statusResponse_(const ContainerAllocator& _alloc)
    : current_state(0)
    , readable_state(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _current_state_type;
  _current_state_type current_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _readable_state_type;
  _readable_state_type readable_state;




  typedef boost::shared_ptr< ::robot_config::user_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_config::user_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct user_statusResponse_

typedef ::robot_config::user_statusResponse_<std::allocator<void> > user_statusResponse;

typedef boost::shared_ptr< ::robot_config::user_statusResponse > user_statusResponsePtr;
typedef boost::shared_ptr< ::robot_config::user_statusResponse const> user_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_config::user_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_config::user_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_config

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::user_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_config::user_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::user_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_config::user_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::user_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_config::user_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_config::user_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bac6da60202660dcc0d978375de35684";
  }

  static const char* value(const ::robot_config::user_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbac6da60202660dcULL;
  static const uint64_t static_value2 = 0xc0d978375de35684ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_config::user_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_config/user_statusResponse";
  }

  static const char* value(const ::robot_config::user_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_config::user_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 current_state\n\
string readable_state\n\
";
  }

  static const char* value(const ::robot_config::user_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_config::user_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_state);
      stream.next(m.readable_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct user_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_config::user_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_config::user_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_state);
    s << indent << "readable_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.readable_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONFIG_MESSAGE_USER_STATUSRESPONSE_H
