// Generated by gencpp from file robot_config/user_status.msg
// DO NOT EDIT!


#ifndef ROBOT_CONFIG_MESSAGE_USER_STATUS_H
#define ROBOT_CONFIG_MESSAGE_USER_STATUS_H

#include <ros/service_traits.h>


#include <robot_config/user_statusRequest.h>
#include <robot_config/user_statusResponse.h>


namespace robot_config
{

struct user_status
{

typedef user_statusRequest Request;
typedef user_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct user_status
} // namespace robot_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_config::user_status > {
  static const char* value()
  {
    return "2d61f0281c2c7175313eb8b7c0ad5a0c";
  }

  static const char* value(const ::robot_config::user_status&) { return value(); }
};

template<>
struct DataType< ::robot_config::user_status > {
  static const char* value()
  {
    return "robot_config/user_status";
  }

  static const char* value(const ::robot_config::user_status&) { return value(); }
};


// service_traits::MD5Sum< ::robot_config::user_statusRequest> should match 
// service_traits::MD5Sum< ::robot_config::user_status > 
template<>
struct MD5Sum< ::robot_config::user_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_config::user_status >::value();
  }
  static const char* value(const ::robot_config::user_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_config::user_statusRequest> should match 
// service_traits::DataType< ::robot_config::user_status > 
template<>
struct DataType< ::robot_config::user_statusRequest>
{
  static const char* value()
  {
    return DataType< ::robot_config::user_status >::value();
  }
  static const char* value(const ::robot_config::user_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_config::user_statusResponse> should match 
// service_traits::MD5Sum< ::robot_config::user_status > 
template<>
struct MD5Sum< ::robot_config::user_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_config::user_status >::value();
  }
  static const char* value(const ::robot_config::user_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_config::user_statusResponse> should match 
// service_traits::DataType< ::robot_config::user_status > 
template<>
struct DataType< ::robot_config::user_statusResponse>
{
  static const char* value()
  {
    return DataType< ::robot_config::user_status >::value();
  }
  static const char* value(const ::robot_config::user_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONFIG_MESSAGE_USER_STATUS_H
